name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.2.3
  - pytest=7.2.2
  - scipy=1.8.1
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
# If have libstdc++.so.6: version `GLIBCXX_3.4.29' not found error:
# sudo apt-get upgrade libstdc++6